# Generated by Django 5.1.7 on 2025-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_expendituredetails_incomedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
