# Generated by Django 5.1.7 on 2025-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_incomedetails_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expendituredetails',
            old_name='source_of_income',
            new_name='source_of_expenditure',
        ),
        migrations.AlterField(
            model_name='expendituredetails',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
