# Generated by Django 5.1.7 on 2025-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_incomedetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
