# Generated by Django 5.1.7 on 2025-03-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_incomedetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituredetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomedetails',
            name='date',
            field=models.DateField(),
        ),
    ]
