# Generated by Django 5.1.7 on 2025-03-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_expendituredetails_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeExpense',
        ),
    ]
