# Generated by Django 5.1.7 on 2025-03-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_delete_incomeexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenditureDetails',
        ),
    ]
