# Generated by Django 5.1.7 on 2025-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_delete_expendituredetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_of_expenditure', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
