# Generated by Django 5.1.7 on 2025-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_incomedetails_category_incomedetails_is_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incomedetails',
            name='is_income',
        ),
        migrations.RemoveField(
            model_name='incomedetails',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='expendituredetails',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expendituredetails',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
